name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compilar y Ejecutar Pruebas con Maven
      # Este comando limpia el proyecto, compila y corre los tests
      # Al final, JaCoCo generará el reporte automáticamente en target/site/jacoco
      run: mvn clean test

    - name: Guardar Reporte de Cobertura como Artefacto
      # Como no tenemos Codecov aún, subimos el HTML para que puedas descargarlo de GitHub
      uses: actions/upload-artifact@v4
      with:
        name: reporte-cobertura
        path: target/site/jacoco/
